// tests/verify.test.ts
//
// 12 scenarios per spec §7.1. Each scenario sets up an in-memory fetcher that
// serves: the REST `/api/programme/:id/metrics` endpoint, the JWK keyset URL,
// the Tier 1 CSV URL, and (where relevant) the Tier 2 CSV URL.
//
// Fixtures are generated by `_generate.ts` and round-trip through src/crypto.ts.

import { beforeAll, describe, expect, it } from 'vitest';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { verify } from '../src/verify.js';
import type { ComputationManifest } from '../src/crypto.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(__dirname, 'fixtures');

const ENDPOINT = 'https://endpoint.test';
const PROGRAMME_ID = 'prog-fixture-1';
const TIER1_URL = 'https://fixtures.local/storage/v1/object/public/computation-exports/prog-fixture-1/t1_v3.csv';
const TIER2_URL = 'https://fixtures.local/storage/v1/object/computation-exports/prog-fixture-1/t2_v3.csv';

interface Fixture {
  manifest: ComputationManifest;
  tier1Csv: string;
  tier2Csv?: string;
  metrics: Record<string, unknown>;
  publicJwk: unknown;
}

let canonicalFixture: Fixture;
let journeysFixture: Fixture;
let sortingFixture: Fixture;
let designFixture: Fixture;
let inputIntegrityFixture: Fixture;

async function loadFixture(slug: string, hasTier2 = false): Promise<Fixture> {
  const manifest = JSON.parse(await readFile(join(FIXTURES, `manifest_${slug}.json`), 'utf8')) as ComputationManifest;
  const tier1Csv = await readFile(join(FIXTURES, `tier1_${slug}.csv`), 'utf8');
  const tier2Csv = hasTier2
    ? await readFile(join(FIXTURES, `tier2_${slug}.csv`), 'utf8')
    : undefined;
  const metrics = JSON.parse(await readFile(join(FIXTURES, `metrics_${slug}.json`), 'utf8')) as Record<string, unknown>;
  const keys = JSON.parse(await readFile(join(FIXTURES, 'keys.json'), 'utf8')) as { publicJwk: unknown };
  return { manifest, tier1Csv, tier2Csv, metrics, publicJwk: keys.publicJwk };
}

beforeAll(async () => {
  canonicalFixture = await loadFixture('canonical_pipeline', true);
  journeysFixture = await loadFixture('enhanced_journeys');
  sortingFixture = await loadFixture('precomputed_sorting');
  designFixture = await loadFixture('designtime_estimation');
  // Input integrity reuses the canonical_pipeline tier data with claim_level set.
  const ii = await loadFixture('canonical_pipeline', true);
  const iiManifest = JSON.parse(
    await readFile(join(FIXTURES, 'manifest_input_integrity.json'), 'utf8'),
  ) as ComputationManifest;
  inputIntegrityFixture = { ...ii, manifest: iiManifest };
});

/**
 * Build a mock fetcher that serves: the REST metrics endpoint, the JWK URL,
 * the Tier 1 CSV URL, and optionally the Tier 2 CSV URL.
 */
function mockFetcher(opts: {
  fixture: Fixture;
  manifestOverride?: ComputationManifest | null;
  tier1Override?: string;
  serveTier2?: boolean;
  serveJwk?: boolean;
  serveMetrics?: boolean;
  tier2RequiredToken?: string;
}) {
  const manifest = opts.manifestOverride === undefined ? opts.fixture.manifest : opts.manifestOverride;
  const tier1 = opts.tier1Override ?? opts.fixture.tier1Csv;
  const serveTier2 = opts.serveTier2 ?? false;
  const serveJwk = opts.serveJwk ?? true;
  const serveMetrics = opts.serveMetrics ?? true;
  const tier2RequiredToken = opts.tier2RequiredToken ?? 'fixture-token';

  return async function fetcher(url: string | URL, init?: RequestInit): Promise<Response> {
    const u = typeof url === 'string' ? url : url.toString();

    // REST metrics endpoint.
    if (u.includes(`/api/programme/${PROGRAMME_ID}/metrics`)) {
      if (!serveMetrics) return new Response(null, { status: 404 });
      const body = {
        programme_id: PROGRAMME_ID,
        published_version: manifest?.published_version ?? 0,
        metrics: opts.fixture.metrics,
        computation_manifest: manifest,
        tier1_csv_url: TIER1_URL,
        tier2_csv_url: TIER2_URL,
      };
      return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
    }

    // JWK keyset.
    if (u.includes('/.well-known/verification-keys')) {
      if (!serveJwk) return new Response(null, { status: 404 });
      const body = { keys: [opts.fixture.publicJwk] };
      return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
    }

    // Tier 1 CSV.
    if (u === TIER1_URL) {
      return new Response(tier1, { status: 200, headers: { 'content-type': 'text/csv' } });
    }

    // Tier 2 CSV.
    if (u === TIER2_URL) {
      if (!serveTier2) return new Response(null, { status: 404 });
      const auth = (init?.headers as Record<string, string> | undefined)?.['authorization'];
      if (auth !== `Bearer ${tier2RequiredToken}`) {
        return new Response('unauthorized', { status: 401 });
      }
      return new Response(opts.fixture.tier2Csv ?? '', { status: 200, headers: { 'content-type': 'text/csv' } });
    }

    return new Response(null, { status: 404 });
  } as unknown as typeof fetch;
}

describe('verify — happy paths (Aggregation Integrity)', () => {
  it('1. canonical_pipeline Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('aggregation_integrity');
      expect(result.tier_run).toBe(1);
    }
  });

  it('2. enhanced_journeys Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: journeysFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') expect(result.claim).toBe('aggregation_integrity');
  });

  it('3. precomputed_sorting Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: sortingFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') expect(result.claim).toBe('aggregation_integrity');
  });

  it('4. designtime_estimation Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: designFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') expect(result.claim).toBe('aggregation_integrity');
  });
});

describe('verify — failure paths', () => {
  it('5. Tier 1 row mutated → MISMATCH(metric_recomputation)', async () => {
    // Mutate the Tier 1 CSV: change the first data row's co2e_kg from 5 to 50.
    const lines = canonicalFixture.tier1Csv.split('\r\n');
    const mutated = [
      lines[0]!,
      lines[1]!.replace(/^5,/, '50,'),
      ...lines.slice(2),
    ].join('\r\n');
    expect(mutated).not.toEqual(canonicalFixture.tier1Csv); // sanity: mutation actually happened
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, tier1Override: mutated }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') {
      // Source-side metrics expect avoided=8, generated=2 → ratio=4. Mutated
      // Tier 1 yields avoided=53, ratio=26.5 → recompute mismatch.
      expect(result.failed_at).toBe('metric_recomputation');
    }
  });

  it('6. Manifest body byte mutated post-signing → MISMATCH(manifest_signature)', async () => {
    const mutated: ComputationManifest = {
      ...canonicalFixture.manifest,
      programme_id: canonicalFixture.manifest.programme_id + '-tampered',
    };
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, manifestOverride: mutated }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') expect(result.failed_at).toBe('manifest_signature');
  });

  it('7. signature.value === "" → NOT_VERIFIABLE_YET (key_pending)', async () => {
    const keyPending: ComputationManifest = {
      ...canonicalFixture.manifest,
      signature: { ...canonicalFixture.manifest.signature, value: '' },
    };
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, manifestOverride: keyPending }),
    });
    expect(result.kind).toBe('not_verifiable_yet');
    if (result.kind === 'not_verifiable_yet') expect(result.manifest_state).toBe('key_pending');
  });

  it('8. No manifest exists → NOT_VERIFIABLE_YET (absent)', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, manifestOverride: null }),
    });
    expect(result.kind).toBe('not_verifiable_yet');
    if (result.kind === 'not_verifiable_yet') expect(result.manifest_state).toBe('absent');
  });
});

describe('verify — Input Integrity (Tier 2)', () => {
  it('9. Tier 2 with Phase 7c input_integrity manifest → VERIFIED Input Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({ fixture: inputIntegrityFixture, serveTier2: true }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('input_integrity');
      expect(result.tier_run).toBe(2);
    }
  });
});

describe('verify — environment isolation & Phase 7c backwards-compat', () => {
  it('10. DEV manifest verified against PROD-style URL where key id is missing → MISMATCH(manifest_signature) with wrong-environment hint', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      // Serve no JWK at the URL — emulates the wrong-environment endpoint case.
      fetcher: mockFetcher({ fixture: canonicalFixture, serveJwk: false }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') {
      expect(result.failed_at).toBe('manifest_signature');
      expect(result.detail).toMatch(/wrong-environment/i);
    }
  });

  it('11. Manifest without claim_level (pre-Phase 7c) → VERIFIED; defaults to Aggregation Integrity', async () => {
    // canonical_pipeline fixture omits claim_level deliberately.
    expect(canonicalFixture.manifest.claim_level).toBeUndefined();
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('aggregation_integrity');
      expect(result.context.manifest_claim_level).toBe('aggregation_integrity');
    }
  });

  it('12. Manifest declares input_integrity but verifier ran --tier 1 → VERIFIED Aggregation Integrity (verifier reports what it checked)', async () => {
    expect(inputIntegrityFixture.manifest.claim_level).toBe('input_integrity');
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: inputIntegrityFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('aggregation_integrity');
      expect(result.context.manifest_claim_level).toBe('input_integrity');
    }
  });
});
