// tests/verify.test.ts
//
// 12 scenarios per spec §7.1. Each scenario sets up an in-memory fetcher that
// serves: the REST `/api/programme/:id/metrics` endpoint, the JWK keyset URL,
// the Tier 1 CSV URL, and (where relevant) the Tier 2 CSV URL.
//
// Fixtures are generated by `_generate.ts` and round-trip through src/crypto.ts.

import { beforeAll, describe, expect, it } from 'vitest';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { verify } from '../src/verify.js';
import type { ComputationManifest } from '../src/crypto.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(__dirname, 'fixtures');

const ENDPOINT = 'https://endpoint.test';
const PROGRAMME_ID = 'prog-fixture-1';
const TIER1_URL = 'https://fixtures.local/storage/v1/object/public/computation-exports/prog-fixture-1/t1_v3.csv';
const TIER2_URL = 'https://fixtures.local/storage/v1/object/computation-exports/prog-fixture-1/t2_v3.csv';
const PATHWAY_URL = 'https://fixtures.local/storage/v1/object/computation-exports/prog-fixture-1/pathway_v3.csv';

interface Fixture {
  manifest: ComputationManifest;
  tier1Csv: string;
  tier2Csv?: string;
  /** v2.0.0 only — the inputs[1] pathway-classification CSV. */
  pathwayCsv?: string;
  metrics: Record<string, unknown>;
  publicJwk: unknown;
}

let canonicalFixture: Fixture;
let journeysFixture: Fixture;
let sortingFixture: Fixture;
let designFixture: Fixture;
let inputIntegrityFixture: Fixture;
let v2PathwayFixture: Fixture;
let v2PathwayMismatchFixture: Fixture;

async function loadFixture(slug: string, hasTier2 = false, hasPathway = false): Promise<Fixture> {
  const manifest = JSON.parse(await readFile(join(FIXTURES, `manifest_${slug}.json`), 'utf8')) as ComputationManifest;
  const tier1Csv = await readFile(join(FIXTURES, `tier1_${slug}.csv`), 'utf8');
  const tier2Csv = hasTier2
    ? await readFile(join(FIXTURES, `tier2_${slug}.csv`), 'utf8')
    : undefined;
  const pathwayCsv = hasPathway
    ? await readFile(join(FIXTURES, `pathway_${slug}.csv`), 'utf8')
    : undefined;
  const metrics = JSON.parse(await readFile(join(FIXTURES, `metrics_${slug}.json`), 'utf8')) as Record<string, unknown>;
  const keys = JSON.parse(await readFile(join(FIXTURES, 'keys.json'), 'utf8')) as { publicJwk: unknown };
  return { manifest, tier1Csv, tier2Csv, pathwayCsv, metrics, publicJwk: keys.publicJwk };
}

beforeAll(async () => {
  canonicalFixture = await loadFixture('canonical_pipeline', true);
  journeysFixture = await loadFixture('enhanced_journeys');
  sortingFixture = await loadFixture('precomputed_sorting');
  designFixture = await loadFixture('designtime_estimation');
  v2PathwayFixture = await loadFixture('v2_pathway', true, true);
  v2PathwayMismatchFixture = await loadFixture('v2_pathway_mismatch', true, true);
  // Input integrity reuses the canonical_pipeline tier data with claim_level set.
  const ii = await loadFixture('canonical_pipeline', true);
  const iiManifest = JSON.parse(
    await readFile(join(FIXTURES, 'manifest_input_integrity.json'), 'utf8'),
  ) as ComputationManifest;
  inputIntegrityFixture = { ...ii, manifest: iiManifest };
});

/**
 * Build a mock fetcher that serves: the REST metrics endpoint, the JWK URL,
 * the Tier 1 CSV URL, and optionally the Tier 2 CSV URL.
 */
function mockFetcher(opts: {
  fixture: Fixture;
  manifestOverride?: ComputationManifest | null;
  tier1Override?: string;
  serveTier2?: boolean;
  serveJwk?: boolean;
  serveMetrics?: boolean;
  tier2RequiredToken?: string;
  /** Serve the inputs[1] pathway CSV at PATHWAY_URL (RLS, requires token). */
  servePathway?: boolean;
  /** Advertise pathway_csv_url in the REST body. Default true. */
  advertisePathwayUrl?: boolean;
  /** Override the served pathway CSV bytes (e.g. tampered → hash break). */
  pathwayOverride?: string;
  /** Override the served REST `metrics` object (e.g. tampered → metrics_hash break). */
  metricsOverride?: Record<string, unknown>;
}) {
  const manifest = opts.manifestOverride === undefined ? opts.fixture.manifest : opts.manifestOverride;
  const tier1 = opts.tier1Override ?? opts.fixture.tier1Csv;
  const serveTier2 = opts.serveTier2 ?? false;
  const serveJwk = opts.serveJwk ?? true;
  const serveMetrics = opts.serveMetrics ?? true;
  const tier2RequiredToken = opts.tier2RequiredToken ?? 'fixture-token';
  const servePathway = opts.servePathway ?? false;
  const advertisePathwayUrl = opts.advertisePathwayUrl ?? true;

  return async function fetcher(url: string | URL, init?: RequestInit): Promise<Response> {
    const u = typeof url === 'string' ? url : url.toString();

    // REST metrics endpoint.
    if (u.includes(`/api/programme/${PROGRAMME_ID}/metrics`)) {
      if (!serveMetrics) return new Response(null, { status: 404 });
      const body = {
        programme_id: PROGRAMME_ID,
        published_version: manifest?.published_version ?? 0,
        metrics: opts.metricsOverride ?? opts.fixture.metrics,
        computation_manifest: manifest,
        tier1_csv_url: TIER1_URL,
        tier2_csv_url: TIER2_URL,
        ...(advertisePathwayUrl ? { pathway_csv_url: PATHWAY_URL } : {}),
      };
      return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
    }

    // JWK keyset.
    if (u.includes('/.well-known/verification-keys')) {
      if (!serveJwk) return new Response(null, { status: 404 });
      const body = { keys: [opts.fixture.publicJwk] };
      return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
    }

    // Tier 1 CSV.
    if (u === TIER1_URL) {
      return new Response(tier1, { status: 200, headers: { 'content-type': 'text/csv' } });
    }

    // Tier 2 CSV.
    if (u === TIER2_URL) {
      if (!serveTier2) return new Response(null, { status: 404 });
      const auth = (init?.headers as Record<string, string> | undefined)?.['authorization'];
      if (auth !== `Bearer ${tier2RequiredToken}`) {
        return new Response('unauthorized', { status: 401 });
      }
      return new Response(opts.fixture.tier2Csv ?? '', { status: 200, headers: { 'content-type': 'text/csv' } });
    }

    // Pathway CSV (inputs[1] — RLS-restricted, same auth contract as Tier 2).
    if (u === PATHWAY_URL) {
      if (!servePathway) return new Response(null, { status: 404 });
      const auth = (init?.headers as Record<string, string> | undefined)?.['authorization'];
      if (auth !== `Bearer ${tier2RequiredToken}`) {
        return new Response('unauthorized', { status: 401 });
      }
      return new Response(opts.pathwayOverride ?? opts.fixture.pathwayCsv ?? '', {
        status: 200,
        headers: { 'content-type': 'text/csv' },
      });
    }

    return new Response(null, { status: 404 });
  } as unknown as typeof fetch;
}

describe('verify — honest per-claim independence (AC20 / D3)', () => {
  it('a scalar metrics_hash mismatch does NOT suppress the pathway verdict (pathway evaluated independently)', async () => {
    // Tier 2 with a valid pathway block + CSV, but TAMPERED served metrics so the
    // scalar metrics_hash binding fails. The pathway claim is signature-bound and
    // must still be established + reported (AC20) — never folded into / gated by
    // the scalar claim. Regression lock for the P7 verify-leg fix (pathway eval
    // moved above the scalar metrics_hash early-return). On the old ordering the
    // metrics_hash mismatch returned before the pathway verdict was computed, so
    // context.pathway was undefined; this test fails on that ordering.
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({
        fixture: v2PathwayFixture,
        serveTier2: true,
        servePathway: true,
        metricsOverride: { ...v2PathwayFixture.metrics, premium_pathway_rate: 0.123456 },
      }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') {
      expect(result.failed_at).toBe('metrics_hash_binding');
      // The pathway claim was recomputed + established independently of the scalar failure.
      expect(result.context.pathway?.status).toBe('verified');
    }
  });
});

describe('verify — happy paths (Aggregation Integrity)', () => {
  it('1. canonical_pipeline Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('aggregation_integrity');
      expect(result.tier_run).toBe(1);
    }
  });

  it('2. enhanced_journeys Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: journeysFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') expect(result.claim).toBe('aggregation_integrity');
  });

  it('3. precomputed_sorting Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: sortingFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') expect(result.claim).toBe('aggregation_integrity');
  });

  it('4. designtime_estimation Tier 1 verified → Aggregation Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: designFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') expect(result.claim).toBe('aggregation_integrity');
  });
});

describe('verify — failure paths', () => {
  it('5. Tier 1 row mutated → MISMATCH(metric_recomputation)', async () => {
    // Mutate the Tier 1 CSV: change the first data row's co2e_kg from 5 to 50.
    const lines = canonicalFixture.tier1Csv.split('\r\n');
    const mutated = [
      lines[0]!,
      lines[1]!.replace(/^5,/, '50,'),
      ...lines.slice(2),
    ].join('\r\n');
    expect(mutated).not.toEqual(canonicalFixture.tier1Csv); // sanity: mutation actually happened
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, tier1Override: mutated }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') {
      // Source-side metrics expect avoided=8, generated=2 → ratio=4. Mutated
      // Tier 1 yields avoided=53, ratio=26.5 → recompute mismatch.
      expect(result.failed_at).toBe('metric_recomputation');
    }
  });

  it('6. Manifest body byte mutated post-signing → MISMATCH(manifest_signature)', async () => {
    const mutated: ComputationManifest = {
      ...canonicalFixture.manifest,
      programme_id: canonicalFixture.manifest.programme_id + '-tampered',
    };
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, manifestOverride: mutated }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') expect(result.failed_at).toBe('manifest_signature');
  });

  it('7. signature.value === "" → NOT_VERIFIABLE_YET (key_pending)', async () => {
    const keyPending: ComputationManifest = {
      ...canonicalFixture.manifest,
      signature: { ...canonicalFixture.manifest.signature, value: '' },
    };
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, manifestOverride: keyPending }),
    });
    expect(result.kind).toBe('not_verifiable_yet');
    if (result.kind === 'not_verifiable_yet') expect(result.manifest_state).toBe('key_pending');
  });

  it('8. No manifest exists → NOT_VERIFIABLE_YET (absent)', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture, manifestOverride: null }),
    });
    expect(result.kind).toBe('not_verifiable_yet');
    if (result.kind === 'not_verifiable_yet') expect(result.manifest_state).toBe('absent');
  });
});

describe('verify — Input Integrity (Tier 2)', () => {
  it('9. Tier 2 with Phase 7c input_integrity manifest → VERIFIED Input Integrity', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({ fixture: inputIntegrityFixture, serveTier2: true }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('input_integrity');
      expect(result.tier_run).toBe(2);
    }
  });
});

describe('verify — environment isolation & Phase 7c backwards-compat', () => {
  it('10. DEV manifest verified against PROD-style URL where key id is missing → MISMATCH(manifest_signature) with wrong-environment hint', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      // Serve no JWK at the URL — emulates the wrong-environment endpoint case.
      fetcher: mockFetcher({ fixture: canonicalFixture, serveJwk: false }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') {
      expect(result.failed_at).toBe('manifest_signature');
      expect(result.detail).toMatch(/wrong-environment/i);
    }
  });

  it('11. Manifest without claim_level (pre-Phase 7c) → VERIFIED; defaults to Aggregation Integrity', async () => {
    // canonical_pipeline fixture omits claim_level deliberately.
    expect(canonicalFixture.manifest.claim_level).toBeUndefined();
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: canonicalFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('aggregation_integrity');
      expect(result.context.manifest_claim_level).toBe('aggregation_integrity');
    }
  });

  it('12. Manifest declares input_integrity but verifier ran --tier 1 → VERIFIED Aggregation Integrity (verifier reports what it checked)', async () => {
    expect(inputIntegrityFixture.manifest.claim_level).toBe('input_integrity');
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: inputIntegrityFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('aggregation_integrity');
      expect(result.context.manifest_claim_level).toBe('input_integrity');
    }
  });
});

describe('verify — pathway composite (v2.0.0 / BRIEFING AC1–AC5)', () => {
  it('AC1. v2 Tier 2 with pathway CSV → scalar VERIFIED + pathway VERIFIED (recompute + L2 projection)', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({ fixture: v2PathwayFixture, serveTier2: true, servePathway: true }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('input_integrity');
      expect(result.context.pathway?.status).toBe('verified');
      expect(result.context.pathway?.projection_checked).toBe(true);
      const passed = result.context.checks.filter((c) => c.passed).map((c) => c.name);
      expect(passed).toContain('pathway_input_hash');
      expect(passed).toContain('pathway_recomputation');
    }
  });

  it('AC5. v2 Tier 1 → scalar VERIFIED, pathway NOT_VERIFIABLE_YET (tier1 — does not fail the scalar)', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 1,
      fetcher: mockFetcher({ fixture: v2PathwayFixture }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.claim).toBe('aggregation_integrity');
      expect(result.context.pathway?.status).toBe('not_verifiable_yet');
      expect(result.context.pathway?.reason).toBe('tier1');
    }
  });

  it('AC5b. v2 Tier 2 but endpoint omits pathway_csv_url → scalar VERIFIED, pathway NOT_VERIFIABLE_YET (no_pathway_url)', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({
        fixture: v2PathwayFixture,
        serveTier2: true,
        servePathway: true,
        advertisePathwayUrl: false,
      }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.context.pathway?.status).toBe('not_verifiable_yet');
      expect(result.context.pathway?.reason).toBe('no_pathway_url');
    }
  });

  it('AC2. v2 Tier 2 with tampered pathway CSV (hash break) → MISMATCH(pathway_input_hash)', async () => {
    const tampered = v2PathwayFixture.pathwayCsv!.replace('10.5', '999.5');
    expect(tampered).not.toEqual(v2PathwayFixture.pathwayCsv);
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({
        fixture: v2PathwayFixture,
        serveTier2: true,
        servePathway: true,
        pathwayOverride: tampered,
      }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') {
      expect(result.failed_at).toBe('pathway_input_hash');
      expect(result.context.pathway?.status).toBe('mismatch');
    }
  });

  it('AC1b. Lying producer (signed block disagrees with honest inputs[1]) → MISMATCH(pathway_recomputation)', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({ fixture: v2PathwayMismatchFixture, serveTier2: true, servePathway: true }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') {
      expect(result.failed_at).toBe('pathway_recomputation');
      expect(result.detail).toMatch(/kg/i);
    }
  });

  it('AC4. Archived 1.0.0 manifest (no pathway_outputs block) still VERIFIES; pathway NOT_VERIFIABLE_YET (no_block)', async () => {
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({ fixture: canonicalFixture, serveTier2: true }),
    });
    expect(result.kind).toBe('verified');
    if (result.kind === 'verified') {
      expect(result.context.pathway?.status).toBe('not_verifiable_yet');
      expect(result.context.pathway?.reason).toBe('no_block');
    }
  });

  it('AC3. v2 manifest with tampered signed block → MISMATCH(manifest_signature) before pathway runs', async () => {
    const tamperedBlock = v2PathwayFixture.manifest.output.pathway_outputs!.map((e, i) =>
      i === 0 ? { ...e, kg: e.kg + 1 } : e,
    );
    const mutated: ComputationManifest = {
      ...v2PathwayFixture.manifest,
      output: { ...v2PathwayFixture.manifest.output, pathway_outputs: tamperedBlock },
    };
    const result = await verify({
      endpoint: ENDPOINT,
      programmeId: PROGRAMME_ID,
      tier: 2,
      supabaseToken: 'fixture-token',
      fetcher: mockFetcher({ fixture: v2PathwayFixture, manifestOverride: mutated, serveTier2: true, servePathway: true }),
    });
    expect(result.kind).toBe('mismatch');
    if (result.kind === 'mismatch') expect(result.failed_at).toBe('manifest_signature');
  });
});
